<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\FIX44.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\FIX44.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuickFIXn.Core" Version="1.14.1" />
    <PackageReference Include="QuickFIXn.FIX44" Version="1.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderAccumulator.Application\OrderAccumulator.Application.csproj" />
    <ProjectReference Include="..\OrderAccumulator.Domain\OrderAccumulator.Domain.csproj" />
  </ItemGroup>

</Project>
